version: '2'
services:
    wishtodo-app:
        image: wishtodo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://wishtodo-mysql:3306/wishtodo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - WISHTODO_MYSQL_PWD=${WISHTODO_MYSQL_PWD}
            - JHIPSTER_REGISTRY_PWD=${JHIPSTER_REGISTRY_PWD}
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 31081:8081
    wishtodo-mysql:
        extends:
            file: mysql.yml
            service: wishtodo-mysql
